version: '3.1'
services:
  currency_db:
    container_name: currency_container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  migrate:
    image: migrate/migrate
    volumes:
      - ../migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@currency_db/postgres?sslmode=disable", "up"]
    links:
      - currency_db